### ISSUE TITLE
Feature request: Range-of-Interest on graphs

### ISSUE THREAD

**Issue by bfschris** [DougEdey/SB_Elsinore_Server#38]
Hi Doug - not sure how to create feature requests, other than here.  Let me know what you prefer for future.

You're probably already hip to what I'm about to describe, but I thought I'd get it on your list, as I, for one, will use the graphs heavily.

I noticed that the graphs can be sometimes difficult to use, in that they often have 1 of 2 defects w/ the vertical scale:

1)  a far-out datapoint (say a zero on server startup) causes all other data to be "scrunched" in a very narrow range.  I checked out the cfg file but wasn't sure how to set max mins there, if that's the place to do it.  Is it feasible to have a range-of-interest setting by the graphs in the UI?

2)  the auto-range on the vertical axis is so tight that small deviations in temp result in visually large movements.  perhaps some "buffering" can be added to either side of the extreme values?  having a manual range setting would of course solve this prob, but I'm assuming you want to retain an auto-range for most people.

One more issue, re: the time axis: it accumulates so many (overlapping) timestamps, I can't read them, even in the full-screen mode.  I'd like to keep the high resolution of every few seconds; perhaps some kind of routine that might evenly space out a set number of timestamps (or a user-settable # of timestamps)?

**Comment by DougEdey** [comment]
Removed overlapping timestamps.
