### ISSUE TITLE
Trigger Re-Order

### ISSUE THREAD

**Issue by F5Brewery** [DougEdey/SB_Elsinore_Server#42]
When reordering or moving triggers they always go above temp/PID, you can then move them down and in place, but it is difficult to tell where they will drop. This was on a RPI with Wheezy and using the Chrome Browser 40.0.2214.94.
![capture](https://cloud.githubusercontent.com/assets/10841082/6033973/ffd3b3ec-abea-11e4-83d6-f25f7f746078.PNG)

**Comment by F5Brewery** [comment]
Errors in Chrome Browser
![errors](https://cloud.githubusercontent.com/assets/10841082/6034124/16b20684-abed-11e4-9604-0cb0e565b313.PNG)

**Comment by DougEdey** [comment]
Now implemented using jQuery UI sortable. Please check all the issues are fixed in the beta branch.

Deleting a step now occurs by dragging a trigger out of the list.

**Comment by DougEdey** [comment]
Actually should be fixed now.
