### ISSUE TITLE
Recorder changes to false upon locking

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#46]
This is something I'm experiencing with the master and beta branch. If I start elsinore, ensuring that recorder setting is set to true in the configuration... I will start with the ability to show temperature graphs as expected. However, if I enter edit mode, then lock the GUI, the graphs disappear. If I check the configuration file upon exit, the recorder option has been set to false somehow.

**Comment by DougEdey** [comment]
Fixed in beta branch, didn't occur in Chrome, only in other browsers.
