### ISSUE TITLE
Floating point issue on plots

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#49]
Last issue! There seems to be some floating point errors on the y-axis of a temp/duty graph. Great work with everything. The new features are exciting.

![floatissue](https://cloud.githubusercontent.com/assets/5422422/6432557/b75d8492-c023-11e4-8d4a-11d7f83edda9.png)

**Comment by DougEdey** [comment]
I couldn't reproduce this, but I have added code that should stop it.
