### ISSUE TITLE
Duty cycle scale missing on graphs

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#51]
For those probes set up with a GPIO, the duty cycle axis labels appear to be missing from their graphs. Whereas an unassociated probe displays the duty cycle axis labels correctly (despite not needing them).

The expanded graphs are using the same colour for duty and temperature now (both red for me)

**Comment by DougEdey** [comment]
Please provide more information, browser, operating system, screenshots, any error messages.

**Comment by jangevaa** [comment]
Safari/OS X Yosemite. Here's some more details:

![error console](https://cloud.githubusercontent.com/assets/5422422/6433495/ad9b780e-c03e-11e4-92ca-eca69cd3a048.png)
