### ISSUE TITLE
Graphing and renaming probes

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#52]
Quite minor: when looking at a graph of all inputs, if a sensor has been renamed, the graph includes both the old and new names rather than reassigning earlier data points to the new probe name. I'm sure this fixes on restart anyways, but in case it's a simple fix thought I'd mention it.

![renamed_probes](https://cloud.githubusercontent.com/assets/5422422/6450465/ffe1d6be-c0f5-11e4-9611-4a6a9398e3f0.png)

**Comment by DougEdey** [comment]
Whilst I can't easily manage the renaming, I fixed the buttons on the graph UI and added a "Reset Recorder" button that'll restart the recorder and create new data.
