### ISSUE TITLE
Time is cyclic

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#54]
This is kind of a funny one, left the recorder running overnight and this is the result:

![cyclictime](https://cloud.githubusercontent.com/assets/5422422/6506332/4f5bf55c-c318-11e4-86c0-024a04de91f6.png)

**Comment by DougEdey** [comment]
This is because the timestamps being sent to the recorder are just time stamps, not datestamps.

This should be an easy fix, I'll check and push a fix tonight.

**Comment by DougEdey** [comment]
The timestamp on the X-axis won't show the date, but hovering over a data point should show it
