### ISSUE TITLE
Unexplained recorder stop for a single input

### ISSUE THREAD

**Issue by jangevaa** [DougEdey/SB_Elsinore_Server#55]
Temperature control is still working as expected, and proper current temperature is shown on the `/controller` page, but changes in temperature are no longer being recorded and graphed for this particular input. Other inputs continue to be recorded and visualized as expected.

![unexplainedstopp](https://cloud.githubusercontent.com/assets/5422422/6546779/387f7f6c-c597-11e4-8251-53e52487142b.png)

**Comment by DougEdey** [comment]
Please provide logs
