### ISSUE TITLE
Can't delete switches and old probes

### ISSUE THREAD

**Issue by bfschris** [DougEdey/SB_Elsinore_Server#64]
Hi Doug - 

I'm not certain whether my inquiry/report constitutes a feature request or a bug, but I can't figure out how to delete switches or old probes which are no longer attached to the system.  Is there a way?

error with old probes, no longer connected:

![image](https://cloud.githubusercontent.com/assets/6607739/7080132/e0a873b4-def2-11e4-88aa-68da11d8fe6b.png)

useless picture showing list of switches I'd like to delete:

![image](https://cloud.githubusercontent.com/assets/6607739/7080142/1019b964-def3-11e4-8af0-412f57f645bc.png)

**Comment by bfschris** [comment]
Doug replied on HomeBrewTalk that switches are removed by clicking and dragging out of view.  I'll leave this bug here for the "old probe" issue.

**Comment by DougEdey** [comment]
Click and drag the probe in edit mode out of the "area" for re-arranging until it shows deleted, then when you drop it it will be gone. You should see messages to indicate that the probe is shutdown in the console log.
