### ISSUE TITLE
No way to edit switch?

### ISSUE THREAD

**Issue by fuzzewuzze** [DougEdey/SB_Elsinore_Server#69]
When setting up my new Elsinore panel, I found no way of editing a switch once it is created and added to the front panel even when in edit mode.  I found that my pins needed to be inverted but could find no way other than editing the elsinore.cfg file to change it once the Switches for pumps were created.

**Comment by jangevaa** [comment]
I think the only option for this is to drag and delete the switch and create a new one.

**Comment by DougEdey** [comment]
Fixed in Beta
