### ISSUE TITLE
java.lang.NumberFormatException while loading BeerXml Recipe

### ISSUE THREAD

**Issue by ngomesdias** [DougEdey/SB_Elsinore_Server#72]
Hi, I'm getting a *java.lang.NumberFormatException: For input string: "3,000"* while loading a BeerXML file generated in BeerSmith 2.2.12
Right before there is also a *WARNING: Fermentation Steps invalid! Expected to find: 1 but the recipe has: 3*  message.

Strange thing is I don't find such a string on the beer file.
I tried this yesterday after pulling last version from GIT.

I'm attaching the log part and also the BeerXML file here:
[BeerXMLParserLog_FermentationStepsInvalid.txt](https://github.com/DougEdey/SB_Elsinore_Server/files/78951/BeerXMLParserLog_FermentationStepsInvalid.txt)
[APA_Recipe.xml.txt](https://github.com/DougEdey/SB_Elsinore_Server/files/78952/APA_Recipe.xml.txt)

Note also that the *WARNING: Unrecognised mash step: Temperature* message at the end of the log.

**Comment by DougEdey** [comment]
I believe that the NumberFormatException is coming from the Water_Grain_Ratio in the Saccharification rest step.

Elsinore only focuses on some specific steps for the mashing, I should modify it

**Comment by ngomesdias** [comment]
Well spotted. Could this be also related to the last message of the Unrecognised mash step ?

**Comment by DougEdey** [comment]
The unrecognized mash step can be easily ignored, it's code I need to address.
